### ISSUE TITLE
import readline from 'readline-promise' not working

### ISSUE THREAD

**Issue by holmrenser** [bhoriuchi/readline-promise#5]
In a current project if I try to import readline I get an empty object:
```js
import readline from 'readline-promise';
console.log(`readline implementation: ${readline}`);
```
```
>>> readline implementation: {}
```

Something similar happens if I try the following:
```js
import * as readline from 'readline-promise';
console.log(`readline implementation: ${readline}`);
```
```
>>>  readline implementation: { default: {}, [Symbol(__esModule)]: true }
```

Which leads me to think the babel transpiled code does not get exported properly.
Upon inspection of the transpiled code I found the following export.
```js
var _readline = require('readline');
var _readline2 = _interopRequireDefault(_readline);

/// SNIP IMPLEMENTATION DETAILS

exports.default = Object.assign({}, _readline2.default, {
  Interface,
  createInterface() {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return new (Function.prototype.bind.apply(Interface, [null].concat(args)))();
  }
});
```

Could it be that something is going wrong here?

**Comment by bhoriuchi** [comment]
what version of nodejs are you using?

**Comment by holmrenser** [comment]
v8.11.1

**Comment by tias79** [comment]
I've got the same issue with v10.5.0.

**Comment by bhoriuchi** [comment]
please provide a repo containing a small project that reproduces the issue that i can clone and use to troubleshoot the issue. thanks.

**Comment by alexch** [comment]
Here you go. https://github.com/BurlingtonCodeAcademy/io/blob/master/quest-readline-promise.js

Output: 
```
$ node quest-readline-promise.js 
/Users/alex/code/io/quest-readline-promise.js:3
const readlineInterface = readline.createInterface({
                                   ^

TypeError: readline.createInterface is not a function
    at Object.<anonymous> (/Users/alex/code/io/quest-readline-promise.js:3:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

$ node -v
v10.9.0
$ npm -v
6.1.0
```
This is on MacOS 10.13.6. I'm using vanilla Node `require`, not `import`, so it's not a Babel thing.

**Comment by kriston13** [comment]
Just chipping in that I've got the same problem using `require`.

**Comment by bhoriuchi** [comment]
@alexch and @kriston13 if you are using require you need to access the default export like

```js
const readline = require('readline-promise').default
```

**Comment by ghost** [comment]
Sorry to revive an old issue, but I have the same problem with 1.0.5 using `import` and Node.js 15.1.0.

```
❯ node screenshot.js
file:///home/nyuszika7h/corellium/screenshot.js:6
let rlp = readline.createInterface({
                   ^

TypeError: readline.createInterface is not a function
    at file:///home/nyuszika7h/corellium/screenshot.js:6:20
    at ModuleJob.run (node:internal/modules/esm/module_job:146:23)
    at async Loader.import (node:internal/modules/esm/loader:165:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

Imported using:
```js
import readline from 'readline-promise'
```
